version: "3.9"



services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


networks:
  postgres-network:
    driver: bridge